//
// Generated by ip_gen_sv_wrapper.tcl
//

module reset_release_module_sv
  import reset_release_module_param_pkg::*;
(
  output wire ninit_done
);

  reset_release_module reset_release_module (
    .ninit_done(ninit_done)
  );


endmodule
